# my details
print("Name: Subin Thapa")
print("Address: Kathmandu")
print("Religion: Hindu")
print("Gender: Male")
print("Contact: 9661875043")
print("Position: Student of Data Science")
print("Marital status: Single")
print("Birthplace: Dhading")
print("Hobby: Trading")
print("Visited Pokhara: Yes")
